export enum XmlObjectIdentifier {
  MATERIAL = 'Material',
  PRODUCTION = 'Production',
  MUSICAL_GENRE = 'Musical genre',
  MUSICAL_WORK_TITLE = 'Musical work title',
  AUDIO_TRACK = 'Audio track',
  AUTHOR = 'Author',
  RECORDING_TIME = 'Recording time',
  RECORD_LABEL = 'Record label',
  INDEX_AUDIO = 'Index audio',
  DIMENSION = 'Dimension',
  PRODUCTION_YEAR = 'Production year',
  RECORDING_LOCALITY = 'Recording locality',
  RECORDING_PLACE = 'Recording place',
  CARRIER_TYPE = 'Carrier type',
  CARRIER_TITLE = 'Carrier title',
}
